cmake_minimum_required(VERSION 3.20)
# actions
function(fRegexIgnoreRBracket vRegexKey vRegexVal)
    set(vRegexVar ${vRegexVal})
    string(REPLACE "(" "\\(" vRegexVar ${vRegexVar})
    string(REPLACE ")" "\\)" vRegexVar ${vRegexVar})
    set(${vRegexKey} ${vRegexVar} PARENT_SCOPE)
endfunction(fRegexIgnoreRBracket)
function(fRegexIgnoreSBracket vRegexKey vRegexVal)
    set(vRegexVar ${vRegexVal})
    string(REPLACE "[" "\\[" ${vRegexKey} ${vRegexVar})
    string(REPLACE "]" "\\]" ${vRegexKey} ${vRegexVar})
    set(${vRegexKey} ${vRegexVar} PARENT_SCOPE)
endfunction(fRegexIgnoreSBracket)
function(fRegexIgnoreCBracket vRegexKey vRegexVal)
    set(vRegexVar ${vRegexVal})
    string(REPLACE "{" "\\{" ${vRegexKey} ${vRegexVar})
    string(REPLACE "}" "\\}" ${vRegexKey} ${vRegexVar})
    set(${vRegexKey} ${vRegexVar} PARENT_SCOPE)
endfunction(fRegexIgnoreCBracket)
function(fRegexIgnoreABracket vRegexKey vRegexVal)
    set(vRegexVar ${vRegexVal})
    fRegexIgnoreRBracket(vRegexVar ${vRegexVar})
    fRegexIgnoreSBracket(vRegexVar ${vRegexVar})
    fRegexIgnoreCBracket(vRegexVar ${vRegexVar})
    set(${vRegexKey} ${vRegexVar} PARENT_SCOPE)
endfunction(fRegexIgnoreABracket)
